### ISSUE TITLE
Permission for travis-ci

### ISSUE THREAD

**Issue by pikepeak** [it-kmitl-2018/group6#19]
Travis-CI ต้องใช้permission จาก admin ครับ ในการเปิดใช้งานครับ ผมจึงขอรบกวนช่วยเปิดใช้งานTravis-CI หรือ ให้permission สำหรับเปิดใช้งานครับ ตามรูปด้านล่างครับ
![image](https://user-images.githubusercontent.com/15785832/37872165-248a16ea-302c-11e8-8126-8e69689c4764.png)
ขอบคุณล่วงหน้าสำหรับความช่วยเหลือครับ

**Comment by champillon** [comment]
Granted
